spring:
  application:
    name: simulator
  config:
    import: classpath:application-platform.yaml
msc:
  events:
    consume: false
  s3:
    enabled: ${MSC_SIMULATION_PAYLOAD_ENABLED:true}
    bucket: msc-simulator
    endpoint: ${MSC_S3_ENDPOINT:}
    access-key: ${MSC_S3_ACCESS_KEY:}
    secret-key: ${MSC_S3_SECRET_KEY:}
